version: '3'
services:
    empressia_php:
        build: ./.docker
        container_name: api_php
        working_dir: /application
        expose:
            - '9000'
        depends_on:
            - empressia_mysql
        volumes:
            - ./:/application

    empressia_nginx:
        image: nginx:1.19.6
        container_name: api_nginx
        ports:
            - 80:80
        volumes:
            - ./:/application
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - empressia_php

    empressia_mysql:
        image: mysql:5.7.33
        container_name: api_mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}

    empressia_mysql_test:
        image: mysql:5.7.33
        container_name: api_mysql_test
        environment:
            - MYSQL_ROOT_PASSWORD=${TEST_DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${TEST_DB_NAME}
            - MYSQL_USER=${TEST_DB_USER}
            - MYSQL_PASSWORD=${TEST_DB_PASSWORD}
